export const FORM_SECTIONS = [
  {
    id: "basicInfo",
    title: "Basic Information",
    subtitle: "Character name, level, and core details",
    required: true,
    lockable: true,
    order: 1,
  },
  {
    id: "house",
    title: "House & School",
    subtitle: "Choose your magical house and school affiliation",
    required: true,
    lockable: true,
    order: 2,
  },
  {
    id: "subclass",
    title: "Subclass",
    subtitle: "Specialized training and advanced features",
    required: true,
    lockable: true,
    order: 3,
  },
  {
    id: "background",
    title: "Background",
    subtitle: "Character background and starting proficiencies",
    required: true,
    lockable: true,
    order: 4,
  },
  {
    id: "level1Choice",
    title: "Level 1 Choice",
    subtitle: "Choose either an Innate Heritage or a Standard Feat",
    required: false,
    lockable: true,
    order: 5,
  },
  {
    id: "asiProgression",
    title: "ASI & Feat Progression",
    subtitle: "Level 4+ Ability Score Improvements and Feat choices",
    required: false,
    lockable: true,
    order: 6,
  },
  {
    id: "skills",
    title: "Skills & Proficiencies",
    subtitle: "Skill proficiencies and expertise",
    required: false,
    lockable: true,
    order: 7,
  },
  {
    id: "toolsLanguages",
    title: "Tool Proficiencies",
    subtitle: "Tool proficiencies",
    required: false,
    lockable: true,
    order: 8,
  },
  {
    id: "abilityScores",
    title: "Ability Scores",
    subtitle: "Set your character's base ability scores",
    required: true,
    lockable: true,
    order: 9,
  },
  {
    id: "hitPoints",
    title: "Hit Points",
    subtitle: "Calculate your character's hit points based on casting style and constitution",
    required: false,
    lockable: true,
    order: 10,
  },
  {
    id: "magicModifiers",
    title: "Magic Modifiers & Wand",
    subtitle: "Wand bonuses and character wand information",
    required: false,
    lockable: true,
    order: 11,
  },
  {
    id: "metamagic",
    title: "Metamagic & Sorcery Points",
    subtitle: "Font of magic and metamagic options",
    required: false,
    lockable: true,
    order: 12,
  },
  {
    id: "notes",
    title: "Character Notes",
    subtitle: "Additional notes, character flaws, backstory etc",
    required: false,
    lockable: true,
    order: 13,
  },
];

export const FORM_MODES = {
  CREATE: "create",
  EDIT: "edit",
  VIEW: "view",
};
